### ISSUE TITLE
Game input dependency

### ISSUE THREAD

**Issue by d6y** [bgaster/rusty-space-invaders#1]
Hello! 👋 Thank you for sharing this. It's great fun 👾 

Apologies if I missed a step in the README, but for me, on macOS, I had to make the following change to `Cargo.toml` to get the game to build:

```diff
-gilrs = { path = "external/gilrs/gilrs" }
+gilrs = "0.7.4"
```

Hope that's of some use - and thanks again!

**Comment by bgaster** [comment]
Thanks, I've updated the Cargo.toml now.
